import Footer from "@/components/common/Footer";
import Navbar from "@/components/common/Navbar";
import "next-cloudinary/dist/cld-video-player.css";

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
